language: python
python:
  - "3.6"
  - "3.7"
  
# command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install h5py --only-binary=h5py
  - pip install git+https://github.com/ucberkeleyseti/blimpy
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install .

# Command to run test
script:
  - cd test; python download_test_data.py; ./run_tests.sh;
    
branches:
  only:
    - master
